BaSP-TG-20: Add and edit employee page
BaSP-m2022/martina-trackgenix-app pull request #1
Opened 2022-05-29 22:38 UTC by JuanMornik

2022-05-31 14:05 UTC, EzeRocco commented on src/Components/Employees/AddForm/AddEmployee.module.css
> +  border: 1px solid grey;
trata de poner el color en hexadecimal. como en la linea 47

2022-05-31 14:07 UTC, EzeRocco commented on src/Components/Employees/index.js
> +  // const addItem = ({ firstName, lastName, phone, email, password, active }) => {
si no usas la función, acodarte de eliminar todo lo comentado

2022-06-01 13:33 UTC, CristianAlcober requested changes
Good job Juan! There are a couple of things that should be revised:

- [x] The 'email' and 'phone' columns have switchet parameters between them.
- [ ] The modal should close by itself after hitting the submit button, in the add or edit employee.
- [ ] The fields do not show how to correct an error.
- [ ] The fields do not show which fields have wrong data.
- [ ] Personally, I think the 'Active' fieldset should not be filled by the user, but that is just a suggestion.
I think that's pretty much the things that should get fixed, I'm sorry I did not saw this sooner.

2022-06-01 16:17 UTC, martumoser commented
> Good job Juan! There are a couple of things that should be revised:
> 
> * [ ]  The 'email' and 'phone' columns have switchet parameters between them.
> * [ ]  The modal should close by itself after hitting the submit button, in the add or edit employee.
> * [ ]  The fields do not show how to correct an error.
> * [ ]  The fields do not show which fields have wrong data.
> * [ ]  Personally, I think the 'Active' fieldset should not be filled by the user, but that is just a suggestion.
>   I think that's pretty much the things that should get fixed, I'm sorry I did not saw this sooner.

2022-06-02 19:04 UTC, martumoser requested changes
La funcionalidad de edit Employee funciona correctamente pero requiere que se actualice la pagina para volver a hacer un get y visualizar esos cambios. En esta problematica buscamos manejar el manejo de data desde el state de react.En este video hay explicacion de como implementar la funcionalidad del edit haciendo uso del state de react: https://youtu.be/cByLkySU4Ho y sino podes preguntarle a tus compañeros o a mi

2022-06-02 19:21 UTC, LucianoAlarcon commented on src/Components/Employees/AddForm/AddEmployee.jsx
> +          <input type="text" name="active" value={userInput.active} onChange={onChange}></input>
Podrias cambiar el active a un select para mejorar la UX

2022-06-02 19:22 UTC, LucianoAlarcon commented on src/Components/Employees/EditForm/EditForm.jsx
> +          <input type="text" name="active" value={userInput.active} onChange={onChange}></input>
Podrias cambiar el active a un select para mejorar un poco mas la experiencia del usuario y que sea mas intuitivo

2022-06-02 19:23 UTC, LucianoAlarcon requested changes
Esta muy bien, falta agregar con que te paso Martu y revisa los comentarios que te deje

2022-06-02 23:02 UTC, LucianoAlarcon approved these changes
🚀🚀

2022-06-02 23:37 UTC, martumoser approved these changes
PR APPROVE

2022-06-03 01:12 UTC, CristianAlcober approved these changes
Excellent job Juan! Everything works splendidly, keep up the good work!

2022-06-03 01:22 UTC, merged