BaSP-TG-33: Footer
BaSP-m2022/martina-trackgenix-app pull request #13
Opened 2022-06-04 22:54 UTC by EzeRocco

My job was to change the footer styles to match the figma. it was not necessary to make the shared components with footer.
- [x] Adpt css Footer to figma

2022-06-04 23:35 UTC, LucianoAlarcon approved these changes

2022-06-05 14:47 UTC, LucasPrat1 approved these changes

2022-06-05 20:29 UTC, martumoser requested changes

2022-06-05 20:29 UTC, martumoser commented on src/Components/Footer/index.js
>    return (
Utilizar ES6 en la linea 4 --> reemplazar` function Footer () `por `const Footer = () => {`

2022-06-05 20:29 UTC, martumoser commented on src/Components/Footer/index.js
>            <li>
Los diferentes li deberían recibirse por props así podemos hacerlo dinamico. El componente recibe por props un array que contiene los diferentes li que queremos mostrar en el footer. De esta forma podemos reutilizar el footer modificando las props que recibe y no necesitamos cambiar el componente entero en caso de querer mostrar mas o menos items o items diferentes. Podría implementar algo así:
```
 {props.routes.map((route) => (
            <li key={route.name}>
              <a href={route.path}>{route.name}</a>
            </li>
}
```
donde props es un array de objetos que tienen route y name. Se entiende la diferencia? cualquier cosa consultame :)

2022-06-05 23:17 UTC, martumoser commented on src/Components/Layout/index.js
> +        ]}
declarar el array con los path y name en una constante links antes del return y pasarle al componente footer ese array como props
```
const links = [
           { path: '/admins', name: 'Admins' },
          { path: '/super-admins', name: 'Super-admins' },
          { path: '/employees', name: 'Employees' },
          { path: '/projects', name: 'Projects' },
          { path: '/time-sheets', name: 'Time-sheets' },
          { path: '/tasks', name: 'Tasks' }]

...

<Footer props={links} />
```

2022-06-05 23:25 UTC, martumoser commented on src/Components/Layout/index.js
> +      <Footer props={arrayRoute}></Footer>
`<Footer props={arrayRoute} />`

2022-06-05 23:32 UTC, martumoser approved these changes

2022-06-05 23:32 UTC, JuanMornik approved these changes

2022-06-05 23:32 UTC, merged