TG-24:List/Delete Employee Page
BaSP-m2022/martina-trackgenix-app pull request #2
Opened 2022-05-29 23:23 UTC by SebastianCocci

2022-05-29 23:36 UTC, EzeRocco commented on src/Components/Employees/ListBody/ListBody.module.css
> +
remove the space here

2022-05-30 13:33 UTC, martumoser requested changes

2022-05-30 16:16 UTC, martumoser requested changes

2022-05-30 16:16 UTC, martumoser commented on src/Components/Employees/index.js
> +  const closeModal = () => {
Estas funciones no son necesarias. Podemos manejar el abrir y cerrar el modal directamente usando el metodo setShowModal y pasandolo por props a los componentees hijos. Eso implica que hay que realizar algunos cambios que te voy a ir marcando en comentarios

2022-05-30 16:16 UTC, martumoser commented on src/Components/Employees/index.js
> +      ) : null}
En este caso buscamos retornar el modal siempre que el showModal esté en true, por lo tanto podemos reemplazar el ternario del if por el short cut && (mas info: https://www.educative.io/edpresso/what-are-javascript-short-circuiting-operators)
El codigo quedaría asi:
```
{showModal && (
        <ModalDelete title={'delete successfully'} show={showModal} setShowModal={setShowModal} />
 )}
```

2022-05-30 16:16 UTC, martumoser commented on src/Components/Employees/index.js
> +        lookModal={lookModal}
Dado que vamos a eliminar la funcion lookModal acá deberiamos **reemplazar** esa prop por:
`setShowModal={setShowModal}`

2022-05-30 16:16 UTC, martumoser commented on src/Components/Employees/ModalDelete/ModalDelete.jsx
> +const ModalDelete = (props) => {
Destructurar las props pata poder identificar claramente cuales son.
`const ModalDelete = ({ title, setShowModal })`

2022-05-30 16:16 UTC, martumoser commented on src/Components/Employees/ModalDelete/ModalDelete.jsx
> +      <button onClick={() => props.closeModal()}>Close</button>
Dado que no vamos a utilizar más la funcion closeModal reemplazar esta linea por:
`<button onClick={() => setShowModal(false)}>Close</button>`

2022-05-30 16:16 UTC, martumoser commented on src/Components/Employees/ListContent/ListContent.jsx
> +      lookModal();
Dado que no vamos a utilizar más la funcion lookModal reemplazar esta linea por:
`setShowModal(true);`

2022-05-30 16:16 UTC, martumoser commented on src/Components/Employees/ListContent/ListContent.jsx
> +const ListContent = (props) => {
Destructurar las props asi podemos identificar claramente cuales son:
`const ListContent = ({ listContent, deleteItem, setShowModal })`

2022-05-30 16:16 UTC, martumoser commented on src/Components/Employees/ListBody/ListBody.module.css
> +.newEm{
Dejar un espacio entre linea 22 y 23 y un espacio entre el final de la palabra y el {

2022-05-30 16:16 UTC, martumoser commented on src/Components/Employees/ListBody/ListBody.module.css
> +}
Dejar un espacio

2022-05-31 11:55 UTC, martumoser approved these changes
PR APPROVE

2022-05-31 13:14 UTC, LucianoAlarcon requested changes

2022-05-31 13:34 UTC, NancyCima approved these changes
Good Job

2022-05-31 14:20 UTC, martumoser commented on src/Components/Employees/index.js
> +        <ModalDelete title={'Delete successfully'} show={showModal} setShowModal={setShowModal} />
Eliminar la prop show modal que no se está usando en el componente modal

2022-05-31 15:01 UTC, merged