BaSP-TG-42: Implement shared components in Project
BaSP-m2022/martina-trackgenix-app pull request #25
Opened 2022-06-07 23:23 UTC by NancyCima

The implementation of the shared components in the project page was divided between Ricardo Dosko and me. 

 In this pull request, I did:

- [ ] implementation of the preloader
- [ ] implementation of modals

Notes:

2022-06-13 01:35 UTC, JuanMornik approved these changes

2022-06-13 11:29 UTC, martumoser requested changes

2022-06-13 11:29 UTC, martumoser commented on src/Components/Shared/Field/Input.jsx
> +                {item.first_name || item.project_name || item.description}
No deberian modificar este componente ya que al ser un componente compartido afecta a todos los otrs recursos en los que se está utilizando

2022-06-13 11:29 UTC, martumoser commented on package.json
> +    "moment": "^2.29.3",
No se deben instalar librerias que no fueron pedidas en la problematica

2022-06-13 21:13 UTC, LucianoAlarcon commented on src/Components/Projects/Form/ProjectForm.jsx
> +  // }-${parseStartDate.getDate()}` || ''
Borra estos comentarios

2022-06-13 21:15 UTC, LucianoAlarcon approved these changes

2022-06-13 21:25 UTC, JuanMornik approved these changes

2022-06-14 11:40 UTC, martumoser approved these changes

2022-06-14 11:41 UTC, merged