BaSP-TG-45: Tasks - Implemented shared components, fixed some problems
BaSP-m2022/martina-trackgenix-app pull request #29
Opened 2022-06-08 02:09 UTC by javierbiselli

- [ ] Implement Rows
- [ ] Implement Fild
- [ ] Implement Button
- [ ] Implement Modal
- [ ] Implement Realoader

2022-06-09 22:59 UTC, javierbiselli commented
> Implementar los cambios incorporados en los formularios y en la funcionalidad de edit y volver a solicitar la review

done

2022-06-10 01:07 UTC, EzeRocco approved these changes

2022-06-10 13:57 UTC, martumoser requested changes

2022-06-10 13:57 UTC, martumoser commented on src/Components/Tasks/index.js
> +        closeForm={openForm}
Esta propiedad  es innecesaria pq no la estas usando del otro lado

2022-06-10 13:57 UTC, martumoser commented on src/Components/Tasks/index.js
> +        <Loader show={loading} />
Este loader aca es innecesario

2022-06-10 13:57 UTC, martumoser commented on src/Components/Tasks/Form/Form.jsx
> +          <Button width={'80px'} height={'30px'} onClick={(e) => onSubmit(e)}>
No es necesario pasar el width y height

2022-06-10 14:19 UTC, javierbiselli commented on src/Components/Tasks/index.js
> +        <Loader show={loading} />
done

2022-06-10 14:19 UTC, javierbiselli commented on src/Components/Tasks/Form/Form.jsx
> +          <Button width={'80px'} height={'30px'} onClick={(e) => onSubmit(e)}>
done

2022-06-10 14:23 UTC, martumoser approved these changes

2022-06-10 20:40 UTC, merged