Feature tg 25 admin list delete
BaSP-m2022/martina-trackgenix-app pull request #3
Opened 2022-05-30 15:13 UTC by LucasPrat1

2022-05-30 19:55 UTC, martumoser requested changes

2022-05-30 19:55 UTC, martumoser commented on src/Components/Admins/index.js
> +  // unnecessary
Eliminar este comment

2022-05-30 19:55 UTC, martumoser commented on src/Components/Admins/ListItem/ListItem.jsx
> +      console.log('response', response);
Eliminar este console.log

2022-05-30 19:55 UTC, martumoser commented on src/Components/Admins/Modal/Modal.jsx
> +  }
Dejar un espacio entre estas lineas

2022-05-30 19:55 UTC, martumoser commented on src/Components/Admins/Modal/Modal.jsx
> +const Modal = (props) => {
Destructurar las props, es decir, especificar cuales son las props que se reciben. En este caso: 
`const Modal = ({ title, closeModal, show })`

2022-05-31 00:57 UTC, NancyCima commented
Good Job!

2022-05-31 19:45 UTC, LucianoAlarcon approved these changes

2022-05-31 20:02 UTC, merged