BaSP-TG-40: Employee
BaSP-m2022/martina-trackgenix-app pull request #30
Opened 2022-06-08 02:21 UTC by EzeRocco

-[x] Implement Rows
-[x] Implement Fild
-[x] Implement Button
-[x] Implement Modal
-[x] Implement Realoader

2022-06-09 16:12 UTC, martumoser requested changes
Implementar los cambios incorporados en los formularios y en el edit y volver a solicitar review

2022-06-09 16:54 UTC, martumoser requested changes

2022-06-09 16:54 UTC, martumoser commented on src/Components/Employees/index.js
> +    const EmpnUpd = list.map((employee) => {
usa camelCase aca

2022-06-09 17:32 UTC, LucasPrat1 approved these changes

2022-06-09 18:08 UTC, LucianoAlarcon approved these changes

2022-06-10 02:15 UTC, CristianAlcober requested changes
Hi Eze! Almost everything works as intended, however there are a few issues:

- [x] Whether you click to add an employee or edit one, the modal does not appear at the center of the screen, instead it appears lower and it prevents the user from using the buttons to 'add' or 'cancel'.
- [x] The 'Name' fieldset stays blank and does not let you fill it with anything.
- [ ] When you send an employee with a wrong or empty fieldset (I did it using tab to reach the button, since I can't see the buttons) the modal appears empty with no message (however, this modal does show at the center of the screen).

Those are all the issues I could find, please fix them as soon as you can. Everything else works wonderfully!

2022-06-10 18:55 UTC, CristianAlcober approved these changes
Excellent job Eze! Everything works nicely!

2022-06-10 19:07 UTC, martumoser approved these changes

2022-06-10 19:07 UTC, merged