BaSP-TG-44-Admins-Implement Shared Comoponents
BaSP-m2022/martina-trackgenix-app pull request #31
Opened 2022-06-08 02:45 UTC by LucasPrat1

Implementation of shared components for each entity

- [x] Implement Rows
- [x] Implement Field
- [x] Implement Button
- [x] Implement Modal
- [x] Implement Realoader

2022-06-08 17:27 UTC, NancyCima reviewed
Hola! Se ve todo bastante bien! Solo te diria de eliminar las carpetas Modal y ModalJavi ya que tecnicamente no las usamos mas. Lo mismo para ListItem :3

2022-06-08 18:07 UTC, CristianAlcober approved these changes
Hi Lucas! I've tested your work and everything seems to be pretty solid. There is just one minor suggestion (do it if you want to):

- [ ]  In the "Add new Admin" modal, the checkboxes at the end do not show any info on which option is for what. I consider this optional to fix, since it does not prevent the user from creating an Admin.

If you can change this, everything would be impeccable, it is up to you to decide. Keep up the good work!

2022-06-09 12:10 UTC, martumoser requested changes
Resolver los comentario marcados por Cristian antes de aprobar y mergear esta pr

2022-06-10 14:25 UTC, martumoser approved these changes

2022-06-10 14:25 UTC, merged