TG-60-Admins: Redux implementation
BaSP-m2022/martina-trackgenix-app pull request #35
Opened 2022-06-12 23:52 UTC by JuanMornik

- [ ] Set actions and constants
- [ ] Set reducer
- [ ] Set thunks
- [ ] Implement List
- [ ] Implement Delete
- [ ] Implement Add
- [ ] Implement Edit

2022-06-13 17:19 UTC, martumoser requested changes

2022-06-13 17:19 UTC, martumoser commented on src/redux/admins/constants.js
> +export const CLEAN_ADMINS_ERROR = 'CLEAN_ADMINS_ERROR';
Estas constantes irian en singular ya que el add, edit y delete agregan, borran y editan un unico admin. Lo mismo para el error.

2022-06-13 17:19 UTC, martumoser commented on src/redux/admins/actions.js
> +export const deleteAdminsSuccess = (adminsId) => ({
reemplazar por adminId en singular

2022-06-13 17:19 UTC, martumoser commented on src/redux/admins/actions.js
> +export const addAdminsSuccess = (admins) => ({
reemplazar por admin en singular

2022-06-14 13:46 UTC, martumoser commented on src/redux/admins/thunks.js
> +
Para mantener consistencia con el resto de las funciones deberias utilizar async await tamb en esta funcion

2022-06-14 23:06 UTC, LucianoAlarcon approved these changes

2022-06-14 23:11 UTC, EzeRocco commented on src/redux/admins/reducer.js
> +
este espacio no es necesario

2022-06-15 00:37 UTC, martumoser approved these changes

2022-06-15 01:10 UTC, merged