BaSP-TG-55: Time-sheets LIST/DELETE - Redux Implement
BaSP-m2022/martina-trackgenix-app pull request #36
Opened 2022-06-13 04:09 UTC by LucianoAlarcon

- [ ] Install Redux Dev Tools
- [ ] Set Actions and Constants
- [ ] Set Reducers
- [ ] Implement Thunks
- [ ] Implement List
- [ ] Implement Delete

2022-06-13 18:34 UTC, JuanMornik requested changes

2022-06-13 18:34 UTC, JuanMornik commented on src/redux/timeSheets/thunks.js
> +    if (confirm('Are you sure you want to delete this Time-Sheet')) {
Esto lo podes manejar desde React en vez de hacerlo desde aca

2022-06-14 23:07 UTC, NancyCima approved these changes
It looks really good! 

The only comment I have its that maybe you can change the constants  "GET_TIMESHEET_xxx" to "GET_TIMESHEETS_xxx" as you tend to get more than one timesheet.

2022-06-14 23:19 UTC, EzeRocco commented on src/redux/timeSheets/actions.js
> +export const deleteTimeSheetSuccess = (timeSheetsId) => ({
remplaza timeSheetsId por su singular (timeSheetId)

2022-06-15 00:21 UTC, JuanMornik approved these changes

2022-06-15 02:25 UTC, merged