BaSP-TG-55: Time-sheets ADD/EDIT - Redux Implement
BaSP-m2022/martina-trackgenix-app pull request #37
Opened 2022-06-13 04:14 UTC by LucasPrat1

- [x] Install redux dev tools
- [x] Set actions and constants
- [x] Set reducer
- [x] Implement thunk
- [x] Implement Add
- [x] Implement Edit

2022-06-13 18:30 UTC, JuanMornik requested changes

2022-06-13 18:30 UTC, JuanMornik commented on src/redux/timeSheets/reducer.js
> +  message: ''
Me gusta la inclusión del mensaje y el error tipo booleano. Lo voy a implementar en my PR

2022-06-13 18:30 UTC, JuanMornik commented on src/redux/timeSheets/actions.js
> +//   type: MESSAGE_TIMESHEET,
Estas lineas comentadas deberías borrarlas si no las vas a usar

2022-06-13 18:30 UTC, JuanMornik commented on src/redux/timeSheets/thunks.js
> +      closeForm();
Esto me gustaría que lo vea Marta, creo que la idea era que no manejemos los modales con redux. Pero no estoy seguro @martumoser

2022-06-13 18:49 UTC, martumoser commented on src/redux/timeSheets/thunks.js
> +      closeForm();
Excactamente como dice Juan, ademas esa funcion no se está recibiendo ni declarando en ningun lado. Todo lo que es manejo de modales lo trabajamos con React

2022-06-14 23:09 UTC, LucianoAlarcon approved these changes

2022-06-14 23:48 UTC, JuanMornik approved these changes

2022-06-15 15:08 UTC, merged