BaSP-TG- 61- Super Admins
BaSP-m2022/martina-trackgenix-app pull request #39
Opened 2022-06-14 01:50 UTC by EzeRocco

-[ x ] Set actions and constants
-[ x ] Set reducer
-[ x ] Implement thunk
-[ x ] Implement List
-[ x ] Implement Delete
-[ x ] Implement Add
-[ x ] Implement Edit

2022-06-14 15:34 UTC, JuanMornik requested changes

2022-06-14 15:34 UTC, JuanMornik commented on src/redux/superAdmins/thunks.js
> +  return (dispatch) => {
Hace esta función asincrónica, asi te queda consistente con las otras

2022-06-14 23:43 UTC, JuanMornik approved these changes

2022-06-15 00:05 UTC, NancyCima approved these changes
Nice Job!!

Remember to check the tasks you completed on the PR's description 👍

2022-06-15 00:56 UTC, CristianAlcober requested changes
Hi Eze, I just saw everything, and I have to say that almost everything seems to work nice, there is just one issue:

- [ ] When adding or editing an item to the list, if you fill wrong one (or more) of the fields, or if you leave them empty and then click on the confirmation button, all the screen turns white and will not change unless you reload the page.

That's it, is just a minor thing to correct, however it is necessary. Everything else works splendidly!

2022-06-15 04:06 UTC, JuanMornik requested changes

2022-06-15 16:31 UTC, LucianoAlarcon requested changes

2022-06-15 16:31 UTC, LucianoAlarcon commented on src/Components/SuperAdmins/index.js
> +          <Button onClick={onClick}> Add Super Admin</Button>
Aca podrias borrarr la funcion de onClick ya que solamente le estas pasando el valor del setShowForm y ejecutar ese estado como funcion directamente
```suggestion
          <Button onClick={() => setShowForm(true)}> Add Super Admin</Button>
```

2022-06-15 16:45 UTC, CristianAlcober approved these changes
Excellent job Eze, everything works nicely, thanks for fixing it!

2022-06-15 23:43 UTC, LucianoAlarcon approved these changes

2022-06-16 00:20 UTC, merged