BaSP-TG-19: List and delete Projects Page
BaSP-m2022/martina-trackgenix-app pull request #4
Opened 2022-05-30 15:28 UTC by LucasPrat1

- [ ] Table list
- [ ] Delete and edit Icon
- [ ] Delete feature
- [ ] Redirect to add/edit form
- [ ] Warning message for delete
- [ ] Success message for confirm delete

2022-05-30 17:37 UTC, martumoser requested changes

2022-05-30 17:37 UTC, martumoser commented on src/Components/Projects/List/list.module.css
> +
Eliminar este espacio

2022-05-30 17:37 UTC, martumoser commented on src/Components/Projects/ListItem/ListItem.js
> +// import React, { useState } from 'react';
Descomentar esta linea

2022-05-30 17:37 UTC, martumoser commented on src/Components/Projects/List/List.js
> +      <ModalError title={'There was an error'} show={showModalError} closeModal={closeModal} />
No es necesario tener un componente para el modal de error. Una de las ventajas de React es que podemos reutilizar componentes, por ende podriamos utilizar un unico modal para mostrar tanto los mensajes de exito como de error

2022-05-30 17:37 UTC, martumoser commented on src/Components/Projects/ListItem/listItem.module.css
> +    }
corregir indentacion de esta llave

2022-05-30 17:37 UTC, martumoser commented on src/Components/Projects/Modal/Modal.js
> +import styles from './modal.module.css';
Falta importar React

2022-05-31 00:29 UTC, NancyCima commented on src/Components/Projects/Modal/modal.module.css
> +    background-color: rgba(0,0,0,0.5);
Hola! Tal vez no tenga mucha importancia en esta etapa pero una vez me marcaron que es mejor ser consistente a la hora de poner los colores (por ej: todos rgba o todos hexadecimales)

2022-06-01 20:59 UTC, LucianoAlarcon approved these changes
Muy buena la solucion para el caso de entidades con populate

2022-06-02 02:47 UTC, LucianoAlarcon approved these changes

2022-06-02 17:24 UTC, martumoser requested changes

2022-06-02 17:24 UTC, martumoser commented on src/Components/Projects/index.js
> +
Incorrecto uso del async. El useEffect es una funcion que no devuelve nada o bien retorna una funcion pero una funcion asincronica devuelve una promesa por que no seria correcto utilizarla en la linea 13. Mas info: https://devtrium.com/posts/async-functions-useeffect
Entiendo tu idea y esta buena. Podrias hacerlo de esta forma:

```
  const fetchData = async () => {
    try {
      const response = await fetch(`${process.env.REACT_APP_API_URL}/super-admins`);
      const data = await response.json();
      saveSuperAdmins(data.data);
    } catch (error) {
      console.error(error);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);
```

2022-06-02 17:24 UTC, martumoser commented on src/Components/Projects/Modal/modal.module.css
> +.container{
Dejar un espacio entre la ultima letra y el {

2022-06-02 18:03 UTC, martumoser requested changes

2022-06-02 18:03 UTC, martumoser commented on src/Components/Projects/FormAdd/AddProject.jsx
> +          </select>
El valor del active selecionado no se guarda correctamente. La forma correcta de hacerlo seria:
     ```
 <select name="active" onChange={(e) => setActive(e.target.value)}>
            <option value={active['true']}>TRUE</option>
            <option value={active['false']}>FALSE</option>
</select>
```

2022-06-03 14:01 UTC, RicardoDosko approved these changes

2022-06-03 14:30 UTC, martumoser approved these changes
Approve

2022-06-03 15:31 UTC, merged