BaSP-TG-62: Employees - Redux implementation
BaSP-m2022/martina-trackgenix-app pull request #40
Opened 2022-06-14 14:21 UTC by javierbiselli

- [x] Install redux dev tools 
- [x] Set actions and constants
- [x] Set reducer
- [x] Implement thunk
- [x] Implement List
- [x] Implement Delete
- [x] Implement Add
- [x] Implement Edit

2022-06-14 15:40 UTC, JuanMornik requested changes

2022-06-14 15:40 UTC, JuanMornik commented on src/redux/employees/thunks.js
> +      console.log(error);
Te quedó este console.log colgado

2022-06-14 15:40 UTC, JuanMornik commented on src/redux/employees/thunks.js
> +      console.log(error);
Este también borralo

2022-06-14 20:13 UTC, javierbiselli commented on src/redux/employees/thunks.js
> +      console.log(error);
borrado

2022-06-14 20:14 UTC, javierbiselli commented on src/redux/employees/thunks.js
> +      console.log(error);
borrado

2022-06-14 21:25 UTC, JuanMornik requested changes

2022-06-14 21:25 UTC, JuanMornik commented on src/Components/Employees/Form/EmployeeForm.jsx
> +  if (error) {
este if también

2022-06-14 21:25 UTC, JuanMornik commented on src/Components/Employees/index.js
> +import { cleanEmployeesError } from '../../redux/employees/actions';
esta action no la necesitamos mas

2022-06-14 21:25 UTC, JuanMornik commented on src/Components/Employees/index.js
> +    dispatch(cleanEmployeesError());
acá no la usas mas

2022-06-14 21:25 UTC, JuanMornik commented on src/redux/employees/actions.js
> +  CLEAN_EMPLOYEES_ERROR
borrar esta linea

2022-06-14 21:25 UTC, JuanMornik commented on src/redux/employees/reducer.js
> +  CLEAN_EMPLOYEES_ERROR
borrar esta linea

2022-06-15 02:45 UTC, JuanMornik approved these changes

2022-06-15 16:35 UTC, martumoser approved these changes

2022-06-15 17:13 UTC, CristianAlcober approved these changes
Wonderful Javi! Everything seems to works nicely, good job!

2022-06-15 19:29 UTC, merged