BaSP-TG-63: Task - Redux implementation
BaSP-m2022/martina-trackgenix-app pull request #41
Opened 2022-06-14 16:13 UTC by SebastianCocci

- [x] Install redux dev tools
- [x] Set actions and constants
- [x] Set reducer
- [x] Implement thunk
- [x] Implement List
- [x] Implement Delete
- [x] Implement Add
- [x] Implement Edit

2022-06-14 23:40 UTC, JuanMornik requested changes

2022-06-14 23:40 UTC, JuanMornik commented on src/Components/Tasks/Form/Form.jsx
> +      dispatch(addTask(userInput));
actualiza esto según lo que vimos para mostrar los modales

2022-06-14 23:40 UTC, JuanMornik commented on src/redux/tasks/reducer.js
> +  error: ''
el error es booleano

2022-06-14 23:40 UTC, JuanMornik commented on src/redux/tasks/reducer.js
> +        error: action.payload
en vez de 'action.payload' va 'true'

2022-06-14 23:40 UTC, JuanMornik commented on src/redux/tasks/reducer.js
> +        error: action.payload
idem get

2022-06-14 23:40 UTC, JuanMornik commented on src/redux/tasks/reducer.js
> +        error: action.payload
idem

2022-06-14 23:40 UTC, JuanMornik commented on src/redux/tasks/reducer.js
> +        error: action.payload
acá también cambiá action.payload por true

2022-06-14 23:40 UTC, JuanMornik commented on src/redux/tasks/thunks.js
> +  return (dispatch) => {
hace esta funcion asincrona como las demas

2022-06-14 23:40 UTC, JuanMornik commented on src/redux/tasks/thunks.js
> +      dispatch(editTaskSuccess(res.data));
y acá agregá los return que vimos para el manejo de los mensajes

2022-06-15 00:22 UTC, JuanMornik approved these changes

2022-06-15 00:44 UTC, JuanMornik commented on src/Components/Tasks/Form/Form.jsx
> +        console.log(error);
esto es console.error(error)

2022-06-15 00:44 UTC, JuanMornik commented on src/Components/Tasks/Form/Form.jsx
> +        console.log(error);
esta también es console.error(error)

2022-06-15 23:46 UTC, LucianoAlarcon approved these changes
🚀🚀🚀

2022-06-16 00:34 UTC, merged