BaSP-TG-71: initial set-up and absolute routes example from layout
BaSP-m2022/martina-trackgenix-app pull request #43
Opened 2022-06-16 23:17 UTC by LucianoAlarcon

- [x] Install react-hook-form and resolvers from joi
- [x] Create json file for absolute routes and example into the Layout
- [x] Create index file into shared folder and export all

2022-06-16 23:32 UTC, javierbiselli approved these changes
Everything ok

2022-06-17 00:14 UTC, LucasPrat1 approved these changes

2022-06-17 12:17 UTC, martumoser requested changes

2022-06-17 12:41 UTC, martumoser approved these changes

2022-06-17 12:41 UTC, merged