BaSP-Feature-TG-84: Employee Sign-Up Form
BaSP-m2022/martina-trackgenix-app pull request #52
Opened 2022-06-21 22:11 UTC by LucianoAlarcon

- [x] Create form using react-hook-form
- [x] Add a POST method whit react redux

2022-06-22 14:44 UTC, LucasPrat1 approved these changes

2022-06-22 16:26 UTC, LucasPrat1 approved these changes

2022-06-23 15:08 UTC, javierbiselli requested changes
.

2022-06-23 15:08 UTC, javierbiselli commented on src/Components/Employee/Sign-up/index.jsx
> +    last_name: joi.string().min(3).max(30).required(),
employees first and last name shoudn't allow numbers or only numbers, it should be only letters

2022-06-23 17:14 UTC, javierbiselli approved these changes
everything good

2022-06-24 00:44 UTC, martumoser approved these changes

2022-06-24 17:34 UTC, merged