BaSP-TG-87: log in front
BaSP-m2022/martina-trackgenix-app pull request #58
Opened 2022-06-28 21:09 UTC by SebastianCocci

- [x] Create a form for Log-in.
- [x] Check form Sign-up (role employee).

2022-06-28 21:28 UTC, JuanMornik approved these changes

2022-06-28 22:22 UTC, LucianoAlarcon approved these changes
🚀🚀🚀

2022-07-01 13:54 UTC, martumoser commented on src/redux/store.js
> +// export default { store };
conservar como estaban originalmente.
`const store = configureStore();`
`export default store;`

2022-07-01 13:56 UTC, martumoser requested changes
Resolver comentarios antes de aprobar y mergear

2022-07-01 17:03 UTC, martumoser commented on src/redux/auth/constants.js
> +export const GET_AUTH_PENDING = 'GET_ME_PENDING';
Corregir el string. Reemplazar por 'GET_AUTH_PENDING'

2022-07-02 15:57 UTC, martumoser approved these changes

2022-07-02 16:04 UTC, merged