Feature tg 21 tasks eze
BaSP-m2022/martina-trackgenix-app pull request #6
Opened 2022-05-31 13:48 UTC by EzeRocco

Creation of the post and put of Task

2022-06-01 15:03 UTC, CristianAlcober requested changes
Excellent job Eze! There are just minor changes to do:

- [x] The visualization of the list of tasks does not show properly, it does not have any labels for the columns.
- [x] When adding a task, the modal for the error is displayed across the whole screen unnecesarily.
- [x] The same happens with the modal for the successfully created task.


Everything else seems to be working properly, keep up the good work!

2022-06-02 14:36 UTC, LucianoAlarcon commented on src/Components/Tasks/index.js
> +  }, []);
Cito mensaje de Martu con respecto al useEffect:

Incorrecto uso del async. El useEffect es una funcion que no devuelve nada o bien retorna una funcion pero una funcion asincronica devuelve una promesa por que no seria correcto utilizarla en la linea 13. Mas info: https://devtrium.com/posts/async-functions-useeffect
Entiendo tu idea y esta buena. Podrias hacerlo de esta forma:

  const fetchData = async () => {
    try {
      const response = await fetch(`${process.env.REACT_APP_API_URL}/super-admins`);
      const data = await response.json();
      saveSuperAdmins(data.data);
    } catch (error) {
      console.error(error);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

2022-06-02 14:38 UTC, LucianoAlarcon requested changes
Buenisimo Eze! Unas cositas para cambiar. El use effect como te marque ahi y deberias poder traerte la data actualizada sin necesidad de realizar una request al get de nuevo. Fijate en el edit como me mostro Marti que se hacia en el video que subio el 1/6 y en el tema del Add podes revisar la clase que ella lo hace muy claro

2022-06-03 04:19 UTC, CristianAlcober approved these changes
A fantastic job Eze, very good!

2022-06-03 14:11 UTC, merged