BaSP-TG-112: Admin Flow - add/edit projects
BaSP-m2022/martina-trackgenix-app pull request #68
Opened 2022-07-17 21:00 UTC by javierbiselli

- [ ] Add project: Adding a project with multiple employees
- [ ] Edit project: Edit a project's data, add or delete employees

Notes: 
- In the add employees and edit employees form you will recieve an alert if:
1. You confirmed but added no employees or deleted all employees
2. You confirmed but added only one employee
3. You confirmed but no employee has a PM role
4. You try to add the same employee twice
5. You added all the employees on the list or there are no employees in the data base

- In the add or edit project form you will recieve an alert if:
1. You try to submit a project with no employees

Notes: 
. IDs will be replaced with first and last names once we fix the server
. There are some console.logs that will be deleted on next commits
. I've made a feature where you could add an employee to the table and this employee would get spliced from the list, and when you delete it from the table, it gets pushed back to the list. This feature caused a LOT of problems and complications so I had to remove it, but I may add it again if there is available time

2022-07-22 15:11 UTC, EzeRocco approved these changes

2022-07-22 19:11 UTC, Shirley1702 commented
Everything is going very well.
It would only change the order of the nav. First projects and then employee.

2022-07-25 17:19 UTC, CristianAlcober requested changes
Hello Javi, almost everything looks pretty good, however I've noticed a little issue:

- [ ] When you edit a project once, and want to do it again the employees asigned to the project show as "undefined undefined".

Fortunately that is the only error I could find, it is a minor issue but still needs to be solved.

2022-07-25 17:40 UTC, CristianAlcober approved these changes
A nice job Javi! All the respective functionallities work as expected!

2022-07-25 18:35 UTC, merged