Feature tg 27 list task page
BaSP-m2022/martina-trackgenix-app pull request #7
Opened 2022-06-01 01:29 UTC by RicardoDosko

-Table list.
-Delete and edit Icon.
-Delete feature.
-Redirect to add/edit form.
-Warming message for delete.
-Success message for confirm delete .

2022-06-01 14:03 UTC, CristianAlcober requested changes
Hello Richard! I see you've worked hard, however i found the following errors while testing the page:

- [ ] The list of task is not showing properly, so it prevents the user from visualizing or editing.
- [ ] The Employee shows a list that should probably be removed before merging.
- [x] The add/edit button leads to a broken link.

I tested this various times with and without Vercel, I think that is pretty much all I see that needs to be fixed.

2022-06-02 19:46 UTC, martumoser commented on src/Components/Tasks/List/index.js
> +import { useEffect, useState } from 'react';
Falta importar React

2022-06-02 19:57 UTC, martumoser commented on src/Components/Tasks/List/index.js
> +  };
Todo lo que es manejo de la data del recurso se debe manejar desde el componente padre, es decir, desde el componente Task. De esta forma, el get de la data se hace en el componente padre y por props pasamos esa data al componente hijo (List).

2022-06-02 19:57 UTC, martumoser commented on src/Components/Tasks/List/index.js
> +  };
Todo lo que es manejo de la data del recurso se debe manejar desde el componente padre, es decir, desde el componente Task. De esta forma, el get de la data se hace en el componente padre y por props pasamos esa data al componente hijo (List).

2022-06-02 22:27 UTC, RicardoDosko commented on public/index.html
> +    crossorigin="anonymous" referrerpolicy="no-referrer" />
Puse erróneamente los estilos ahí, ya los elimino.

2022-06-02 22:28 UTC, RicardoDosko commented on src/Components/Tasks/List/Button/index.js
> +export default Btn;
Si, estuve viendo un post de como implementar eso, ya lo elimino.

2022-06-02 22:29 UTC, RicardoDosko commented on src/Components/Tasks/List/index.js
> +  };
Gracias por aclararme eso, estaba medio perdido.

2022-06-02 23:28 UTC, JuanMornik requested changes
Como comentario general.  El archivo "index.js" de la carpeta Row y el de la carpeta List deberían ser .jsx así consistente con lo de los demás

2022-06-02 23:28 UTC, JuanMornik commented on src/Components/Tasks/List/index.js
> +const List = (props) => {
Acá deberias destructurar las props cuando las recibe. Es decir, lo que estas haciendo en la linea de abajo pasaselo directamente como parametro.
Te deberia quedar asi: `const List = ({ listTask, handleDelete })`

2022-06-02 23:28 UTC, JuanMornik commented on src/Components/Tasks/List/index.js
> +  const { listTask, handleDelete } = props;
Y esta linea borrala

2022-06-02 23:28 UTC, JuanMornik commented on src/Components/Tasks/row/index.js
> +const Row = (props) => {
Lo mismo que en list, desestructurá las props y borrá la linea de abajo

2022-06-02 23:41 UTC, JuanMornik requested changes

2022-06-02 23:41 UTC, JuanMornik commented on src/Components/Tasks/index.js
> +    fetch('http://localhost:4000/tasks')
Para la url del fetch lo correcto seria usar las variables de entorno que nos compartieron la semana pasada (las del archivo .env). Porque vos ahí le fijaste una ruta y la hiciste visible, la idea es que ese tipo de cosas solo se pueda acceder si tenes el archivo .env y que a su vez si modificas ese archivo se modifique la ruta en todo tu código.
Te debería quedar asi: ``${process.env.REACT_APP_API_URL}/tasks`

2022-06-02 23:41 UTC, JuanMornik commented on src/Components/Tasks/index.js
> +      await fetch(`http://localhost:4000/tasks/${id}`, {
lo mismo con este fetch y su url

2022-06-03 00:59 UTC, RicardoDosko commented on src/Components/Tasks/List/index.js
> +const List = (props) => {
Esto lo consultaria, realmente no lo creo necesario, de hecho no me parece que este mal asi.
@martumoser

2022-06-03 01:01 UTC, RicardoDosko commented on src/Components/Tasks/index.js
> +    fetch('http://localhost:4000/tasks')
genial esto, no me habia dado cuenta, ahora lo corrijo.

2022-06-03 01:01 UTC, RicardoDosko commented on src/Components/Tasks/index.js
> +      await fetch(`http://localhost:4000/tasks/${id}`, {
tambien ya lo corrijo!

2022-06-03 01:43 UTC, martumoser requested changes

2022-06-03 01:43 UTC, martumoser commented on src/Components/Tasks/List/index.js
> +const List = (props) => {
No esta mal como lo hiciste pero para mantener consistencia con lo hecho en el resto del codigo estaria bueno que sigas la sugerencia de Juan

2022-06-03 13:41 UTC, martumoser approved these changes

2022-06-03 13:49 UTC, LucianoAlarcon approved these changes

2022-06-03 15:09 UTC, JuanMornik approved these changes

2022-06-03 18:34 UTC, CristianAlcober approved these changes
A fantastic job Richard! Keep it up!

2022-06-03 18:36 UTC, merged