TG-109: Profile Employee
BaSP-m2022/martina-trackgenix-app pull request #70
Opened 2022-07-22 14:04 UTC by EzeRocco

- [ ] View informaton
- [ ] Add edit info
- [ ] New style

2022-07-24 22:06 UTC, javierbiselli requested changes
esta bien el codigo pero no deberias modificar el shared component de input porque nos va a deformar los inputs a todos, sino lo que podrias hacer es modificar solo los inputs de profile, podes hacerlo poniendo una className a los inputs, si no funciona, proba poniendoles id

2022-07-26 02:17 UTC, javierbiselli approved these changes
quedo lindo

2022-07-26 02:18 UTC, JuanMornik approved these changes

2022-07-26 20:04 UTC, CristianAlcober approved these changes
Excellent Eze, the profile looks amazing! There is a tiny little issue... When the user edits its profile and proceeds to another section (like timesheets) and returns to profile the changes in the info get undone. However, I don't consider it a critical issue, since it can be fixed by logout and login again, then the info will display correctly. If you have available time, I recommend to solve this. 
That would be all, keep up the good job!

2022-07-26 20:10 UTC, merged