BaSP-Feature-TG-110: Employee time-sheet
BaSP-m2022/martina-trackgenix-app pull request #71
Opened 2022-07-24 15:50 UTC by LucianoAlarcon

- [ ] List of projects
- [ ] Calendar to upload hours
- [ ] 1 timesheet for day
- [ ] Total hours on the week

2022-07-24 19:23 UTC, javierbiselli requested changes

2022-07-24 19:23 UTC, javierbiselli commented on src/Components/Employee/TimeSheet/Form/Form.jsx
> +              <Button onClick={() => reset()}>Reset Form</Button>
luchito este boton de reset no funciona, cuando lo apretas te hace un submit, puede ser porque esta dentro del form, capaz se soluciona sacando los botones del form, lo mismo para el de arriba cuando el previoustimesheet no existe, al apretarlo te ejecuta la validacion y no deberia, deberia solo resetear, tambien puede ser por la misma razon

2022-07-24 19:30 UTC, javierbiselli requested changes

2022-07-24 19:30 UTC, javierbiselli commented on src/Components/Employee/TimeSheet/Form/Form.jsx
> +              <Button onClick={() => reset()}>Reset Form</Button>
luchito este boton de reset no funciona, te hace un submit cuando lo apretas, lo mismo el de abajo para cuando no tenes previous timesheet, te ejecuta la validacion cuando lo apretas y no deberia, deberia solo resetear, puede ser porque tenes los botones dentro del form, posible solucion es poner los botones por fuera del form

2022-07-25 00:40 UTC, javierbiselli approved these changes
quedo muy buena!

2022-07-25 20:32 UTC, JuanMornik approved these changes
Well done! Congratulations (?

2022-07-26 20:19 UTC, CristianAlcober approved these changes
Fantastic Lucho! Everything seems to work exceptionally! There is a tiny bug with the buttons to switch between the calendars, once you press one, it stays grey instead of returning to green. As I said, it is a minor thing, should get fixed but only if you have time available.

2022-07-26 20:21 UTC, merged