BaSP-Hotfix-TG-126: Login error message
BaSP-m2022/martina-trackgenix-app pull request #74
Opened 2022-07-25 12:54 UTC by NancyCima

In this hotfix branch:

- [x] An alert was added because the modal for the error at login was not working correctly.

2022-07-25 13:08 UTC, EzeRocco approved these changes

2022-07-25 18:14 UTC, javierbiselli requested changes

2022-07-25 18:14 UTC, javierbiselli commented on src/Components/Auth/Login/index.jsx
> +      <Modal isOpen={showModal} handleClose={() => setShowModal(false)}>
borremos el modal y los states del modal de mas arriba si vamos a dejar el mensaje con alert

2022-07-25 22:23 UTC, NancyCima commented on src/Components/Auth/Login/index.jsx
> +      <Modal isOpen={showModal} handleClose={() => setShowModal(false)}>
okii

2022-07-26 00:49 UTC, JuanMornik approved these changes

2022-07-26 02:16 UTC, javierbiselli approved these changes

2022-07-26 20:45 UTC, CristianAlcober approved these changes
Nice solution Nancy! Well done!

2022-07-26 20:49 UTC, merged