BaSP-TG-120: Styles
BaSP-m2022/martina-trackgenix-app pull request #76
Opened 2022-07-27 05:39 UTC by Shirley1702

Change the styles of: home, nav, footer, login, sign up and modal.
I don't like modal. but it can be improved, if anyone has any ideas.

2022-07-27 12:59 UTC, LucasPrat1 commented on src/Components/Auth/SignUp/index.jsx
> +              <div className={styles.activeNone}>
esto no debería estar, se tiene que sacar el input de ACTIVE

2022-07-27 13:09 UTC, LucasPrat1 requested changes
no deberías subir en esta rama los TEST, deberías hacer dos ramas diferentes

2022-07-27 13:09 UTC, LucasPrat1 commented on src/Components/Home/Home.jsx
> +        <img className={styles.logoTrackgenix} src={logoTrack} />
las imágenes deberian estar guardadas en la carpeta public, no en src

2022-07-27 13:09 UTC, LucasPrat1 commented on src/Components/Shared/Modal/Modal.jsx
> +import exit from 'Assets/Imgs/exit.png';
esta imagen no es necesaria, se puede hacer con un div

2022-07-28 01:48 UTC, JuanMornik requested changes

2022-07-28 01:48 UTC, JuanMornik commented on src/Components/Admin/Home/index.js
> +        {user && <h2>W{user?.firstName + ' ' + user?.lastName}</h2>}
Te quedó una W colgada ahí

2022-07-28 02:48 UTC, Shirley1702 commented on src/Components/Home/Home.jsx
> +        <img className={styles.logoTrackgenix} src={logoTrack} />
no, emmm lo habia probado como vos me decis. pero hable con puch y me explico que tenia que hacer una carpeta dentro de src

2022-07-28 02:49 UTC, Shirley1702 commented on src/Components/Shared/Modal/Modal.jsx
> +import exit from 'Assets/Imgs/exit.png';
i know. jaja

2022-07-28 02:51 UTC, Shirley1702 commented on src/Components/Admin/Home/index.js
> +        {user && <h2>W{user?.firstName + ' ' + user?.lastName}</h2>}
listttttuuuuu

2022-07-28 03:41 UTC, JuanMornik approved these changes

2022-07-28 19:25 UTC, LucasPrat1 commented on src/Components/Home/Home.jsx
> +        <img className={styles.logoTrackgenix} src={logoTrack} />
Para que quede consistente con el resto de la app deberia estar en public. Pero no importa ya fue

2022-07-28 19:26 UTC, LucasPrat1 approved these changes

2022-07-28 21:39 UTC, merged