BaSP-TG-22: Add and edit features for admins
BaSP-m2022/martina-trackgenix-app pull request #9
Opened 2022-06-01 01:52 UTC by javierbiselli

- [ ] Add route on Layout Component
- [ ] Create Form
- [ ] On editing, form should show previuos info
- [ ] Add feature
- [ ] Edit feature
- [ ] Success message for edit and add
- [ ] Error messages for edit and add

2022-06-02 14:42 UTC, LucianoAlarcon commented on src/Components/Admins/index.js
> +  }, []);
Cito mensaje de Martu con respecto al uso del useEffect:
Incorrecto uso del async. El useEffect es una funcion que no devuelve nada o bien retorna una funcion pero una funcion asincronica devuelve una promesa por que no seria correcto utilizarla en la linea 13. Mas info: https://devtrium.com/posts/async-functions-useeffect
Entiendo tu idea y esta buena. Podrias hacerlo de esta forma:

  const fetchData = async () => {
    try {
      const response = await fetch(`${process.env.REACT_APP_API_URL}/super-admins`);
      const data = await response.json();
      saveSuperAdmins(data.data);
    } catch (error) {
      console.error(error);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

2022-06-02 14:45 UTC, LucianoAlarcon requested changes
Buenisimo Javi! Unas cositas para cambiar. El use effect como te marque ahi y deberias poder traerte la data actualizada sin necesidad de realizar una request al get de nuevo. Fijate en el edit como me mostro Marti que se hacia en el video que subio el 1/6 y en el tema del Add podes revisar la clase que ella lo hace muy claro. Ademas te falta actualizar y traerte los ultimos cambios de master. Podes usar la biblia de Git y Github (https://docs.google.com/document/d/1XKUKiUeDPjc-Wz83Pg3XPpDw548n4ThvJM29Lx3kra4/edit?usp=sharing), en la parte de solucionar conflictos y traerte los ultimos cambios de master

2022-06-02 20:34 UTC, javierbiselli commented on src/Components/Admins/index.js
> +  }, []);
fixed

2022-06-03 13:23 UTC, martumoser approved these changes
PR APPROVE

2022-06-03 13:28 UTC, LucianoAlarcon approved these changes

2022-06-03 13:50 UTC, merged